repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: no-commit-to-branch
      args: ['--branch', 'master', "--branch", "main"]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    - id: pyupgrade
      args: ["--py37-plus"]
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      pass_filenames: true
-   repo: https://github.com/seddonym/import-linter
    rev: v1.7.0
    hooks:
    - id: import-linter
      stages: [manual]