repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: no-commit-to-branch
      args: ['--branch', 'master', "--branch", "main"]
-   repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
    -   id: absolufy-imports
        exclude: _vendor|vendored|examples|examples_with_napari
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
    - id: pycln
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    - id: pyupgrade
      args: ["--py38-plus", "--keep-runtime-typing"]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      pass_filenames: true
-   repo: https://github.com/seddonym/import-linter

    rev: v1.7.0
    hooks:
    - id: import-linter
      stages: [manual]