repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: no-commit-to-branch
      args: ['--branch', 'master', "--branch", "main"]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
    - id: pyupgrade
      args: ["--py37-plus"]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      pass_filenames: true
-   repo: https://github.com/seddonym/import-linter
    rev: v1.2.7
    hooks:
    - id: import-linter
      stages: [manual]